<?php

return array(
  'mailing_backend_alternate1' => array(
    'group_name' => 'Mailing Preferences',
    'group' => 'mailing',
    'name' => 'mailing_backend_alternate1',
    'type' => 'Array',
    'html_type' => 'checkbox',
    'default' => 0,
    'add' => '4.6',
    'title' => 'Mailing Backend Alternate (First)',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'First alternate mailing backend',
    'help_text' => 'First alternate mailing backend',
  ),
  'mailing_backend_alternate2' => array(
    'group_name' => 'Mailing Preferences',
    'group' => 'mailing',
    'name' => 'mailing_backend_alternate2',
    'type' => 'Array',
    'html_type' => 'checkbox',
    'default' => 0,
    'add' => '4.6',
    'title' => 'Mailing Backend Alternate (Second)',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Second alternate mailing backend',
    'help_text' => 'Second alternate mailing backend',
  ),
  'reGroupName1' => array(
    'group_name' => 'Mailing Preferences',
    'group' => 'mailing',
    'name' => 'reGroupName1',
    'type' => 'String',
    'html_type' => 'textarea',
    'default' => 0,
    'add' => '4.6',
    'title' => 'Regular expressions for First Mailing Backend Alternate',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Regular expressions for First Mailing Backend Alternate',
    'help_text' => 'Regular expressions for First Mailing Backend Alternate',
  ),
  'reGroupName2' => array(
    'group_name' => 'Mailing Preferences',
    'group' => 'mailing',
    'name' => 'reGroupName2',
    'type' => 'String',
    'html_type' => 'textarea',
    'default' => 0,
    'add' => '4.6',
    'title' => 'Regular expressions for Second Mailing Backend Alternate',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Regular expressions for Second Mailing Backend Alternate',
    'help_text' => 'Regular expressions for Second Mailing Backend Alternate',
  ),
);
